// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "provider": string;
      "apiBase": string;
      "apiKey": string;
      "model": string;
      "modelCatalog": string;
      "aiVerifiedAt": string;
      "embeddingReuseAI": boolean;
      "embeddingProvider": string;
      "embeddingBase": string;
      "embeddingKey": string;
      "embeddingModel": string;
      "embeddingCatalog": string;
      "embeddingVerifiedAt": string;
      "retrievalProvider": string;
      "retrievalApiKey": string;
      "retrievalVerifiedAt": string;
      "maxEvidenceTokens": number;
      "storageDirectory": string;
      "language": string;
    };
  }
}

